# Generated by Django 4.2.6 on 2023-10-22 04:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Details')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('image_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Image Source')),
                ('video_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Video Link')),
                ('video_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Video Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('editor_reviewed', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Editor Reviewed')),
                ('total_view', models.PositiveIntegerField(default=0, verbose_name='Total View (*Do not edit)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory', to_field='uniqueId', verbose_name='Category')),
                ('city_corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation', to_field='uniqueId', verbose_name='City Corporation')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continent', to_field='uniqueId', verbose_name='Continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country', to_field='uniqueId', verbose_name='Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', to_field='uniqueId', verbose_name='District')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division', to_field='uniqueId', verbose_name='Division')),
                ('pourosava', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.pourosava', to_field='uniqueId', verbose_name='Pourosava')),
                ('related_post', models.ManyToManyField(blank=True, to='news.post', verbose_name='Related Post Suggestion')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.reporter', to_field='uniqueId', verbose_name='Reporter')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newssubcategory', to_field='uniqueId', verbose_name='Sub Category')),
                ('tag', models.ManyToManyField(blank=True, to='categories.poststag', verbose_name='Tags')),
                ('thana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.thana', to_field='uniqueId', verbose_name='Thana')),
                ('turisum_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.turisumspot', to_field='uniqueId', verbose_name='Tourism Spot')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.union', to_field='uniqueId', verbose_name='Union')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', to_field='uniqueId', verbose_name='Upozila')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode', to_field='uniqueId', verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'All Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
