# Generated by Django 4.2.4 on 2023-09-29 14:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Post/images/webp')),
                ('videoLink', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('editor_reviewed', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continents')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.reporter')),
                ('subcategoryId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newssubcategory')),
                ('tag', models.ManyToManyField(blank=True, to='categories.poststag')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'All Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
