# Generated by Django 4.2.4 on 2023-09-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('reporter', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continents'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district'),
        ),
        migrations.AlterField(
            model_name='post',
            name='division',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.reporter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newssubcategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upozila',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode'),
        ),
    ]
