# Generated by Django 4.2.6 on 2023-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='editor_reviewed',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Editor Review'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='This unique Id will be auto generate'),
        ),
    ]
