# Generated by Django 4.2.4 on 2023-09-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_categoryid_alter_post_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(blank=True, to='news.post'),
        ),
    ]
