# Generated by Django 4.2.6 on 2023-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_editor_reviewed_alter_post_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_highlight_on_section',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Highlight on section'),
        ),
    ]
