# Generated by Django 4.2.4 on 2023-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_related_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
