# Generated by Django 4.2.6 on 2023-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_is_highlight_on_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Updated At'),
        ),
    ]
