# Generated by Django 4.2.4 on 2023-09-30 18:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_code_zippostalcode_zipcode_poststag_uniqueid_and_more'),
        ('reporter', '0001_initial'),
        ('news', '0004_post_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continents', verbose_name='Continent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='post',
            name='division',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='post',
            name='editor_reviewed',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Editor Reviewed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Post/images/webp', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(blank=True, to='news.post', verbose_name='Related Post Suggation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.reporter', verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newssubcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='categories.poststag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Total View(*Do not edit)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upozila',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', verbose_name='Upozila'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True, verbose_name='URL(will be auto generated)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='videoLink',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode', verbose_name='Zip Code'),
        ),
    ]
