# Generated by Django 4.2.4 on 2023-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_post_categoryid_alter_post_continent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
