# Generated by Django 4.2.4 on 2023-10-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
        ('categories', '0008_turisumspot_delete_touristspot'),
        ('news', '0006_alter_post_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city_corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation', verbose_name='City Corporation'),
        ),
        migrations.AddField(
            model_name='post',
            name='pourosava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.pourosava', verbose_name='Pourosava'),
        ),
        migrations.AddField(
            model_name='post',
            name='thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.thana', verbose_name='Thana'),
        ),
        migrations.AddField(
            model_name='post',
            name='turisum_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.turisumspot', verbose_name='Turisum Spot'),
        ),
        migrations.AddField(
            model_name='post',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.union', verbose_name='Union'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continents', verbose_name='Continent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='post',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.reporter', verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newssubcategory', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='upozila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', verbose_name='Upozila'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode', verbose_name='Zip Code'),
        ),
    ]
