# Generated by Django 4.2.4 on 2023-10-09 12:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_post_city_corporation_post_pourosava_post_thana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image0',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
