# Generated by Django 4.2.4 on 2023-10-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_post_city_corporation_post_pourosava_post_thana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Post/images/webp', verbose_name='Image'),
        ),
    ]
