# Generated by Django 4.2.4 on 2023-10-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_turisumspot_delete_touristspot'),
        ('news', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Post/images/webp', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='image0',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Post/images/webp', verbose_name='Image0'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.ManyToManyField(blank=True, to='news.post', verbose_name='Related Post Suggestion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Total View (*Do not edit)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='turisum_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.turisumspot', verbose_name='Tourism Spot'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True, verbose_name='URL (will be auto-generated)'),
        ),
    ]
