# Generated by Django 4.2.4 on 2023-10-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_post_image0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image0',
        ),
    ]
