# Generated by Django 4.2.4 on 2023-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_post_image_post__image_post_image0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='Post/images/webp', verbose_name='_Image'),
        ),
    ]
