# Generated by Django 4.2.4 on 2023-10-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_post__image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image0',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
