# Generated by Django 4.2.4 on 2023-10-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_post_image0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image0',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imageurl',
        ),
    ]
