# Generated by Django 4.2.4 on 2023-10-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_image0_post_image_remove_post__image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subcategoryId',
            new_name='subcategory',
        ),
    ]
