# Generated by Django 4.2.4 on 2023-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_categoryid_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
