# Generated by Django 4.2.6 on 2023-10-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
