# Generated by Django 4.2.6 on 2023-10-22 17:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('news', '0001_initial'),
        ('categories', '0001_initial'),
        ('feature', '0001_initial'),
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=30)),
                ('option_two', models.CharField(max_length=30)),
                ('option_three', models.CharField(max_length=30)),
                ('option_one_count', models.PositiveIntegerField(default=0)),
                ('option_two_count', models.PositiveIntegerField(default=0)),
                ('option_three_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField()),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Website Title')),
                ('tagLine', models.TextField(blank=True, default='', verbose_name='Tag Line/ Slogan')),
                ('url', models.CharField(blank=True, default='', max_length=50, verbose_name='Website URL')),
                ('logo', models.ImageField(blank=True, default='', upload_to='website_info/logo', verbose_name='Website Logo')),
                ('favicon', models.ImageField(blank=True, default='', upload_to='website_info/icon', verbose_name='Website Favicon icon')),
                ('newsThumbnail', models.ImageField(blank=True, default='', upload_to='website_info/newsThumbnail', verbose_name='News Thumbnail')),
                ('facebook_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook URL')),
                ('twitter_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Twitter URL')),
                ('youtube_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Youtube URL')),
                ('instagram_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Instagram URL')),
                ('linkedin_url', models.CharField(blank=True, default='', max_length=200, verbose_name='Linkedin URL')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='Address')),
                ('contact1', models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Nubmer 1')),
                ('contact2', models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Nubmer 2')),
                ('email', models.CharField(blank=True, default='', max_length=200, verbose_name='Email Address')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=200, verbose_name='Whatsapp Number')),
                ('telegram', models.CharField(blank=True, default='', max_length=200, verbose_name='Telegram Number')),
                ('google_map', models.TextField(blank=True, default='', verbose_name='Google Map')),
                ('copyright_text', models.CharField(default='', max_length=500)),
                ('about_us', ckeditor.fields.RichTextField(blank=True, default='')),
                ('contact_us', ckeditor.fields.RichTextField(blank=True, default='')),
                ('advertisement_policy', ckeditor.fields.RichTextField(blank=True, default='')),
                ('privacy_policy', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Privacy Policy / Terms of Use')),
                ('comment_policy', ckeditor.fields.RichTextField(blank=True, default='')),
                ('android_app_url', models.CharField(blank=True, default='', max_length=200)),
                ('ios_app_url', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Info',
                'verbose_name_plural': 'Website Infos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(blank=True, max_length=10, verbose_name='Background Color(Must be in Hexadecimal)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sectionBox/images/webp')),
                ('title', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adbox_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adbox_top', to='advertisement.advertisement', to_field='uniqueId')),
                ('heighlighted', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.post', to_field='uniqueId', verbose_name='Heighlighted News')),
                ('items', models.ManyToManyField(blank=True, to='categories.newscategory')),
                ('items10', models.ManyToManyField(blank=True, to='article.articlewritter')),
                ('items2', models.ManyToManyField(blank=True, to='categories.newssubcategory')),
                ('items3', models.ManyToManyField(blank=True, to='categories.poststag')),
                ('items4', models.ManyToManyField(blank=True, to='categories.continent')),
                ('items5', models.ManyToManyField(blank=True, to='categories.country')),
                ('items6', models.ManyToManyField(blank=True, to='categories.division')),
                ('items7', models.ManyToManyField(blank=True, to='categories.district')),
                ('items8', models.ManyToManyField(blank=True, to='categories.citycorporation')),
                ('items9', models.ManyToManyField(blank=True, to='article.articlecategory')),
            ],
            options={
                'verbose_name': 'Section Box',
                'verbose_name_plural': 'Section Boxs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='categories.newscategory', verbose_name='In Nav Categories(Do not select 8 more)')),
                ('feature', models.ManyToManyField(blank=True, to='feature.feature', verbose_name='In News feature')),
                ('news', models.ManyToManyField(blank=True, to='categories.continent', verbose_name='In Nav News')),
                ('news2', models.ManyToManyField(blank=True, to='categories.country', verbose_name='In Nav News')),
                ('news3', models.ManyToManyField(blank=True, to='categories.division', verbose_name='In Nav News')),
                ('news4', models.ManyToManyField(blank=True, to='categories.district', verbose_name='In Nav News')),
                ('news5', models.ManyToManyField(blank=True, to='categories.citycorporation', verbose_name='In Nav News')),
                ('news6', models.ManyToManyField(blank=True, to='categories.turisumspot', verbose_name='In Nav News')),
            ],
            options={
                'verbose_name': 'Navigation Bar',
                'verbose_name_plural': 'Navigation Bar',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HeadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headlines', models.ManyToManyField(blank=True, to='news.post', verbose_name='Headlines')),
            ],
            options={
                'verbose_name': 'Headline',
                'verbose_name_plural': 'Headlines',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headNews', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.post', to_field='uniqueId', verbose_name='Head Line News')),
            ],
            options={
                'verbose_name': 'Cover',
                'verbose_name_plural': 'Cover',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_at', models.DateTimeField()),
                ('items', models.ManyToManyField(blank=True, to='news.post', verbose_name='Breaking News')),
            ],
            options={
                'verbose_name': 'Breaking News',
                'verbose_name_plural': 'Breaking News',
                'ordering': ['-updated_at'],
            },
        ),
    ]
