# Generated by Django 4.2.6 on 2023-10-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteinfo',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Website Info', 'verbose_name_plural': 'Website Infos'},
        ),
    ]
