# Generated by Django 4.2.6 on 2023-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecategory_status_articlewritter_status_and_more'),
        ('webInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='news',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='news2',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='news3',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='news4',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='news5',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='news6',
        ),
        migrations.AddField(
            model_name='navigation',
            name='openion',
            field=models.ManyToManyField(blank=True, to='article.articlecategory', verbose_name='In Nav Openion'),
        ),
    ]
