# Generated by Django 4.2.6 on 2023-10-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionbox',
            name='serial',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
