# Generated by Django 4.2.6 on 2023-10-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('webInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteinfo',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Website Info', 'verbose_name_plural': 'Website Infos'},
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='feature',
        ),
        migrations.AlterField(
            model_name='cover',
            name='headNews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.post', to_field='uniqueId', verbose_name='Head Line News'),
        ),
    ]
