# Generated by Django 4.2.6 on 2023-10-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0002_alter_websiteinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='feature',
        ),
    ]
