# Generated by Django 4.2.6 on 2023-10-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_featurepost_description'),
        ('webInfo', '0002_alter_websiteinfo_options_remove_navigation_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='feature',
            field=models.ManyToManyField(blank=True, to='feature.feature', verbose_name='In News feature'),
        ),
    ]
