# Generated by Django 4.2.6 on 2023-10-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_alter_advertisement_addbox'),
        ('webInfo', '0002_sectionbox_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionbox',
            name='adbox_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adbox_top', to='advertisement.advertisement', to_field='uniqueId'),
        ),
    ]
