# Generated by Django 4.2.6 on 2023-11-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0002_remove_navigation_news_remove_navigation_news2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='openion',
        ),
    ]
