# Generated by Django 4.2.4 on 2023-10-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0002_navigation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline',
            old_name='items',
            new_name='headlines',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
    ]
