# Generated by Django 4.2.6 on 2023-10-22 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('news', '0001_initial'),
        ('webInfo', '0003_navigation_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Cover', 'verbose_name_plural': 'Cover'},
        ),
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Headline', 'verbose_name_plural': 'Headlines'},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Poll', 'verbose_name_plural': 'Polls'},
        ),
        migrations.AddField(
            model_name='sectionbox',
            name='items10',
            field=models.ManyToManyField(blank=True, to='article.articlewritter'),
        ),
        migrations.AddField(
            model_name='sectionbox',
            name='items9',
            field=models.ManyToManyField(blank=True, to='article.articlecategory'),
        ),
        migrations.AlterField(
            model_name='sectionbox',
            name='heighlighted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.post', to_field='uniqueId', verbose_name='Heighlighted News'),
        ),
    ]
