# Generated by Django 4.2.6 on 2023-11-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_is_highlight_on_section'),
        ('categories', '0002_poststag_status'),
        ('webInfo', '0003_remove_navigation_openion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadLineNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headNews', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='news.post', verbose_name='Head Line News')),
            ],
            options={
                'verbose_name': 'Head Line News',
                'verbose_name_plural': 'Head Line News',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeHighlightedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlightedNews', models.ManyToManyField(to='news.post', verbose_name='Highlighted News')),
            ],
            options={
                'verbose_name': 'Home Highlighte dNews',
                'verbose_name_plural': 'Home Highlighted News',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='adbox_top',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='details',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='heighlighted',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items10',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items2',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items3',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items4',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items5',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items6',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items7',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items8',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='items9',
        ),
        migrations.RemoveField(
            model_name='sectionbox',
            name='title',
        ),
        migrations.AddField(
            model_name='sectionbox',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory'),
        ),
        migrations.AlterField(
            model_name='sectionbox',
            name='serial',
            field=models.PositiveIntegerField(default=0, verbose_name='Serial Number'),
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
