# Generated by Django 4.2.4 on 2023-10-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_delete_navigation'),
        ('feature', '0001_initial'),
        ('webInfo', '0003_rename_items_headline_headlines_delete_navigation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ManyToManyField(blank=True, to='feature.feature', verbose_name='In News feature')),
                ('in_categories', models.ManyToManyField(blank=True, to='categories.newscategory', verbose_name='In Nav Categories(Do not select 8 more c)')),
                ('in_news', models.ManyToManyField(blank=True, to='categories.continents', verbose_name='In Nav News')),
                ('in_news2', models.ManyToManyField(blank=True, to='categories.country', verbose_name='In Nav News')),
                ('in_news3', models.ManyToManyField(blank=True, to='categories.division', verbose_name='In Nav News')),
                ('in_news4', models.ManyToManyField(blank=True, to='categories.district', verbose_name='In Nav News')),
                ('in_news5', models.ManyToManyField(blank=True, to='categories.citycorporation', verbose_name='In Nav News')),
                ('in_news6', models.ManyToManyField(blank=True, to='categories.turisumspot', verbose_name='In Nav News')),
            ],
            options={
                'verbose_name': 'Navigation Bar',
                'verbose_name_plural': 'Navigation Bar',
            },
        ),
    ]
