# Generated by Django 4.2.4 on 2023-10-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0004_navigation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Navigation Bar', 'verbose_name_plural': 'Navigation Bar'},
        ),
    ]
