# Generated by Django 4.2.6 on 2023-11-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_is_highlight_on_section'),
        ('webInfo', '0004_headlinenews_homehighlightednews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headNews', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='news.post', verbose_name='Head/Main News')),
            ],
            options={
                'verbose_name': 'Head/Main News',
                'verbose_name_plural': 'Head/Main News',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='HeadLineNews',
        ),
    ]
