# Generated by Django 4.2.6 on 2023-10-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0004_alter_cover_options_alter_headline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='google_map',
            field=models.TextField(blank=True, default='', verbose_name='Google Map'),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='linkedin_url',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Linkedin URL'),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Telegram Number'),
        ),
    ]
