# Generated by Django 4.2.4 on 2023-10-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_post__image'),
        ('categories', '0010_delete_navigation'),
        ('webInfo', '0005_alter_navigation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='items',
            field=models.ManyToManyField(blank=True, to='news.post', verbose_name='Breaking News'),
        ),
        migrations.AlterField(
            model_name='headline',
            name='headlines',
            field=models.ManyToManyField(blank=True, to='news.post', verbose_name='Headlines'),
        ),
        migrations.AlterField(
            model_name='sectionbox',
            name='items',
            field=models.ManyToManyField(blank=True, to='categories.newscategory'),
        ),
    ]
