# Generated by Django 4.2.6 on 2023-10-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0005_websiteinfo_google_map_websiteinfo_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
