# Generated by Django 4.2.6 on 2023-10-22 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0006_poll_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteinfo',
            name='total_view',
        ),
    ]
