# Generated by Django 4.2.4 on 2023-10-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_delete_navigation'),
        ('webInfo', '0006_alter_breakingnews_items_alter_headline_headlines_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='in_news',
            new_name='news',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='in_news2',
            new_name='news2',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='in_news3',
            new_name='news3',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='in_news4',
            new_name='news4',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='in_news5',
            new_name='news5',
        ),
        migrations.RenameField(
            model_name='navigation',
            old_name='in_news6',
            new_name='news6',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='in_categories',
        ),
        migrations.AddField(
            model_name='navigation',
            name='categories',
            field=models.ManyToManyField(to='categories.newscategory', verbose_name='In Nav Categories(Do not select 8 more)'),
        ),
    ]
