# Generated by Django 4.2.6 on 2023-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0007_alter_sectionbox_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='editor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='head_editor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Head Editor'),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Publisher'),
        ),
    ]
