# Generated by Django 4.2.6 on 2023-11-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_is_highlight_on_section'),
        ('webInfo', '0008_websiteinfo_editor_websiteinfo_head_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakingnews',
            name='items',
        ),
        migrations.AddField(
            model_name='breakingnews',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='news.post', verbose_name='Breaking News'),
        ),
    ]
