# Generated by Django 4.2.6 on 2023-11-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0009_remove_breakingnews_items_breakingnews_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakingnews',
            old_name='item',
            new_name='post',
        ),
    ]
