# Generated by Django 4.2.6 on 2023-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0010_rename_item_breakingnews_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteinfo',
            name='editor',
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='editor_admin',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Editor admin / নির্বাহী সম্পাদক'),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='editor_news',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='News Editor/ বার্তা সম্পাদক'),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='copyright_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='head_editor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Head Editor/ সম্পাদক '),
        ),
        migrations.AlterField(
            model_name='websiteinfo',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Publisher/ প্রকাশক'),
        ),
    ]
