# Generated by Django 4.2.6 on 2023-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0010_rename_item_breakingnews_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionbox',
            name='side',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right')], default=0, verbose_name='recent news side'),
        ),
    ]
