# Generated by Django 4.2.6 on 2023-12-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_poststag_status'),
        ('webInfo', '0011_remove_websiteinfo_editor_websiteinfo_editor_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='categories',
            field=models.ManyToManyField(to='categories.newscategory', verbose_name='In Nav Categories(Do not select 9 more)'),
        ),
    ]
