# Generated by Django 4.2.6 on 2023-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0012_alter_navigation_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteinfo',
            name='tagLine',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Tag Line/ Slogan'),
        ),
    ]
