# Generated by Django 4.2.6 on 2023-12-07 10:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0013_alter_websiteinfo_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='openion_gideline',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
