# Generated by Django 4.2.6 on 2023-12-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInfo', '0011_sectionbox_side'),
        ('webInfo', '0014_websiteinfo_openion_gideline'),
    ]

    operations = [
    ]
