# Generated by Django 4.2.6 on 2023-10-22 04:41

import advertisement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20, unique=True, verbose_name='Unique Id will be generated automatically')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Advertisement Box',
                'verbose_name_plural': 'Advertisement Boxes',
            },
        ),
        migrations.CreateModel(
            name='AdCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField( max_length=20, unique=True, verbose_name='Unique Id will be generated automatically')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Advertisement/company/')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Company Link')),
                ('payment_due', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement Company',
                'verbose_name_plural': 'Advertisement Companies',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20, unique=True, verbose_name='Unique Id will be generated automatically')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Advertisement/Adds/')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('embed_code', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('stop_at', models.DateTimeField()),
                ('addBox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adbox', to_field='uniqueId')),
                ('add_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adcompany', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
