# Generated by Django 4.2.6 on 2023-10-21 23:35

import advertisement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcompany',
            name='uniqueId',
            field=models.CharField(default=advertisement.models.randomString, max_length=20, unique=True, verbose_name='Unique Id will be generated automatically'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='add_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adcompany', to_field='uniqueId'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Unique Id will be generated automatically'),
        ),
    ]
