# Generated by Django 4.2.6 on 2023-11-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbox',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Unique Id'),
        ),
        migrations.AlterField(
            model_name='adcompany',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Unique Id '),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='addBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adbox'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='add_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adcompany'),
        ),
    ]
