# Generated by Django 4.2.6 on 2023-10-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcompany',
            options={'ordering': ['-created_at'], 'verbose_name': 'Advertisement Company', 'verbose_name_plural': 'Advertisement Companies'},
        ),
        migrations.AlterField(
            model_name='adcompany',
            name='name',
            field=models.CharField(default='asdf', max_length=200, verbose_name='Company Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Unique Id will be generated automatically'),
        ),
    ]
