# Generated by Django 4.2.6 on 2023-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_adcompany_options_alter_adcompany_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbox',
            options={'ordering': ['total_view'], 'verbose_name': 'Advertisement Box', 'verbose_name_plural': 'Advertisement Boxes'},
        ),
        migrations.AlterField(
            model_name='adbox',
            name='position',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adbox',
            name='size',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
