# Generated by Django 4.2.6 on 2023-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_adbox_uniqueid_alter_adcompany_uniqueid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbox',
            name='box_position_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
