# Generated by Django 4.2.6 on 2023-10-22 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_adcompany_uniqueid_alter_advertisement_add_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AddField(
            model_name='adbox',
            name='uniqueId',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Unique Id will be generated automatically'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='addBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adbox', to_field='uniqueId'),
        ),
    ]
