# Generated by Django 4.2.6 on 2023-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_adbox_box_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbox',
            name='box_position_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Must Give a Box Position Id(Unique))'),
        ),
    ]
