# Generated by Django 4.2.6 on 2023-10-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_adbox_options_alter_adbox_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='addBox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adbox', to_field='uniqueId'),
        ),
    ]
