# Generated by Django 4.2.6 on 2023-11-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_adbox_box_position_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adbox',
            options={'ordering': ['box_position_id'], 'verbose_name': 'Advertisement Box', 'verbose_name_plural': 'Advertisement Boxes'},
        ),
    ]
