# Generated by Django 4.2.6 on 2023-10-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_addbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Unique Id will be generated automatically'),
        ),
    ]
