# Generated by Django 4.2.6 on 2023-10-22 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_advertisement_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='addBox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advertisement.adbox', to_field='uniqueId'),
        ),
    ]
