# Generated by Django 4.2.4 on 2023-10-09 10:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20, verbose_name='Category name in English without Space and comma')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Article/Category/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleWritter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20, verbose_name='Writter name in English without Space and comma')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Article/Writer/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
