# Generated by Django 4.2.6 on 2023-10-22 17:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporter', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20, unique=True, verbose_name='Category name in English without Space and comma')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Article/Category/')),
                ('serial', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleWritter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20, unique=True, verbose_name='Writer name in English without Space and comma')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Article/Writer/')),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Article Writter',
                'verbose_name_plural': 'Article Writters',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Unique Id will be generated automatically')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Image')),
                ('image_source', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('editor_reviewed', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_category', to='article.articlecategory', to_field='uniqueId')),
                ('related_article', models.ManyToManyField(blank=True, to='article.article')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_reporter', to='reporter.reporter', to_field='uniqueId')),
                ('tag', models.ManyToManyField(blank=True, to='categories.poststag')),
                ('writter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_writter', to='article.articlewritter', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
