# Generated by Django 4.2.4 on 2023-10-09 10:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_thana_upozila_and_more'),
        ('reporter', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Article/Images')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('editor_reviewed', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.articlecategory')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.reporter')),
                ('tag', models.ManyToManyField(to='categories.poststag')),
                ('writter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.articlewritter')),
            ],
        ),
    ]
