# Generated by Django 4.2.6 on 2023-10-22 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AlterModelOptions(
            name='articlewritter',
            options={'ordering': ['name'], 'verbose_name': 'Article Writter', 'verbose_name_plural': 'Article Writters'},
        ),
        migrations.AlterField(
            model_name='article',
            name='writter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.articlewritter'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='articlewritter',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlewritter',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
