# Generated by Django 4.2.6 on 2023-10-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AlterModelOptions(
            name='articlewritter',
            options={'verbose_name': 'Article Writter', 'verbose_name_plural': 'Article Writters'},
        ),
    ]
