# Generated by Django 4.2.6 on 2023-10-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AlterModelOptions(
            name='articlewritter',
            options={'ordering': ['name'], 'verbose_name': 'Article Writter', 'verbose_name_plural': 'Article Writters'},
        ),
    ]
