# Generated by Django 4.2.4 on 2023-10-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_delete_navigation'),
        ('article', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_article',
            field=models.ManyToManyField(blank=True, to='article.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='categories.poststag'),
        ),
    ]
