# Generated by Django 4.2.6 on 2023-10-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articlewritter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
