# Generated by Django 4.2.6 on 2023-10-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlewritter',
            options={'verbose_name': 'Article Writter', 'verbose_name_plural': 'Article Writters'},
        ),
    ]
