# Generated by Django 4.2.6 on 2023-11-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecategory_status_articlewritter_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['total_view'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.RenameField(
            model_name='articlecategory',
            old_name='name',
            new_name='title',
        ),
    ]
