# Generated by Django 4.2.4 on 2023-10-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_related_article_alter_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
