# Generated by Django 4.2.6 on 2023-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_highlight_on_section',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Highlight on section'),
        ),
    ]
