# Generated by Django 4.2.6 on 2023-10-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlewritter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlewritter',
            options={'ordering': ['name'], 'verbose_name': 'Article Writter', 'verbose_name_plural': 'Article Writters'},
        ),
        migrations.AlterField(
            model_name='articlewritter',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
