# Generated by Django 4.2.6 on 2023-10-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
        ('article', '0003_alter_articlecategory_name_alter_articlewritter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_category', to='article.articlecategory', to_field='uniqueId'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_reporter', to='reporter.reporter', to_field='uniqueId'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Unique Id will be generated automatically'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_writter', to='article.articlewritter', to_field='uniqueId'),
        ),
    ]
