# Generated by Django 4.2.6 on 2023-10-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='serial',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor_reviewed',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Category name in English without Space and comma'),
        ),
        migrations.AlterField(
            model_name='articlewritter',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Writter name in English without Space and comma'),
        ),
    ]
