# Generated by Django 4.2.6 on 2023-10-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_category_alter_article_reported_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['serial'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
    ]
