# Generated by Django 4.2.6 on 2023-10-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articlecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['name'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
    ]
