# Generated by Django 4.2.6 on 2023-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='Reporter/'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
