# Generated by Django 4.2.6 on 2023-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
