# Generated by Django 4.2.6 on 2023-10-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_alter_reporter_image_alter_reporter_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reporter/Stuff', 'verbose_name_plural': 'Reporters/Stuffs'},
        ),
        migrations.AlterField(
            model_name='reporter',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
