# Generated by Django 4.2.4 on 2023-09-29 14:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/CityCorporation/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'City Corporation',
                'verbose_name_plural': 'City Corporations',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Continents/')),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Continent',
                'verbose_name_plural': 'Continents',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Country/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continents')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/District/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Division/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Category/')),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('serial', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='PostsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Tags/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Post Tag',
                'verbose_name_plural': 'Post Tags',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Upozila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Upozila/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district')),
            ],
            options={
                'verbose_name': 'Upozila',
                'verbose_name_plural': 'Upozilas',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='ZipPostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/ZipPostalCode/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('cityCorporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila')),
            ],
            options={
                'verbose_name': 'Zip Postal Code',
                'verbose_name_plural': 'Zip Postal Codes',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='NewsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/SubCategory/')),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory')),
            ],
            options={
                'verbose_name': 'News Sub Category',
                'verbose_name_plural': 'News Sub Categories',
                'ordering': ['serial'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division'),
        ),
        migrations.AddField(
            model_name='citycorporation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district'),
        ),
        migrations.AddField(
            model_name='citycorporation',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division'),
        ),
    ]
