# Generated by Django 4.2.6 on 2023-10-22 04:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='City Corporation Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/CityCorporation/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'City Corporation',
                'verbose_name_plural': 'City Corporations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=20, unique=True, verbose_name='Continent Name in English without Space')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Continents/')),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Continent',
                'verbose_name_plural': 'Continents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Country Name in English without Space')),
                ('cCode', models.CharField(max_length=4, unique=True, verbose_name='Country Code')),
                ('name', models.CharField(max_length=50)),
                ('capital', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Country/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continent', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='District Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/District/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Category Name in English without Space')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Category/')),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('serial', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'News Category',
                'verbose_name_plural': 'News Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PostsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Tag Name in English without Space')),
                ('title', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Tags/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Post Tag',
                'verbose_name_plural': 'Post Tags',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Upozila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Upozila Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Upozila/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Upozila',
                'verbose_name_plural': 'Upozilas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZipPostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Zip Postal Code + Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=20, unique=True)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/ZipPostalCode/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('cityCorporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation', to_field='uniqueId')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', to_field='uniqueId')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Zip Postal Code',
                'verbose_name_plural': 'Zip Postal Codes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Union Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Union/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('upozila', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Union',
                'verbose_name_plural': 'Unions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TurisumSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Tourist Spot Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/TurisumSpot/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('cityCorporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation', to_field='uniqueId')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', to_field='uniqueId')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.union', to_field='uniqueId')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', to_field='uniqueId')),
                ('zipCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Turisum Spot',
                'verbose_name_plural': 'Turisum Spots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Thana Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Thana/')),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('cityCorporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation', to_field='uniqueId')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', to_field='uniqueId')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Thana',
                'verbose_name_plural': 'Thanas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pourosava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Pourosava Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Pourosava/')),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', to_field='uniqueId')),
                ('upozila', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Pourosava',
                'verbose_name_plural': 'Pourosavas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Sub Category Name in English without Space')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/SubCategory/')),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.newscategory', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'News Sub Category',
                'verbose_name_plural': 'News Sub Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, unique=True, verbose_name='Division Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Division/')),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country', to_field='uniqueId')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division', to_field='uniqueId'),
        ),
        migrations.AddField(
            model_name='citycorporation',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', to_field='uniqueId'),
        ),
        migrations.AddField(
            model_name='citycorporation',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division', to_field='uniqueId'),
        ),
    ]
