# Generated by Django 4.2.6 on 2023-10-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pourosava',
            name='upozila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', to_field='uniqueId'),
        ),
    ]
