# Generated by Django 4.2.4 on 2023-09-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cCode',
            field=models.CharField(default=1, max_length=4, verbose_name='Country Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
