# Generated by Django 4.2.6 on 2023-10-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zippostalcode',
            options={'ordering': ['zipCode'], 'verbose_name': 'Zip Postal Code', 'verbose_name_plural': 'Zip Postal Codes'},
        ),
        migrations.AlterField(
            model_name='citycorporation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='City Corporation Name'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Continent Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cCode',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='sortDetails',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='division',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Division Name'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='poststag',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Tag Name'),
        ),
        migrations.AlterField(
            model_name='pourosava',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Pourosava Name'),
        ),
        migrations.AlterField(
            model_name='thana',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Thana Name'),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Union Name'),
        ),
        migrations.AlterField(
            model_name='upozila',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Upozila Name'),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Post office Name'),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='zipCode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Zip Postal Code'),
        ),
    ]
