# Generated by Django 4.2.4 on 2023-09-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_country_ccode_country_capital_country_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zippostalcode',
            old_name='code',
            new_name='zipCode',
        ),
        migrations.AddField(
            model_name='poststag',
            name='uniqueId',
            field=models.CharField(default=1, max_length=50, verbose_name='Tag Name in English without Space'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citycorporation',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citycorporation',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='City Corporation Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='continents',
            name='uniqueId',
            field=models.CharField(max_length=20, verbose_name='Continent Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='Country Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='district',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='District Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='division',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='Division Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='Category Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='newssubcategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newssubcategory',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='Sub Category Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='poststag',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upozila',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upozila',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='Upozila Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='uniqueId',
            field=models.CharField(max_length=50, verbose_name='Zip Postal Code Name in English without Space'),
        ),
    ]
