# Generated by Django 4.2.4 on 2023-10-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pourosava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, verbose_name='Pourosava Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Pourosava/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pourosava',
                'verbose_name_plural': 'Pourosavas',
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, verbose_name='Thana Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Thana/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Thana',
                'verbose_name_plural': 'Thanas',
            },
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=150, verbose_name='Union Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Union/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Union',
                'verbose_name_plural': 'Unions',
                'ordering': ['serial'],
            },
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='zippostalcode',
            name='division',
        ),
        migrations.AlterField(
            model_name='citycorporation',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citycorporation',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='continents',
            name='url',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upozila',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='cityCorporation',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='upozila',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='union',
            name='upozila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila'),
        ),
        migrations.AddField(
            model_name='thana',
            name='cityCorporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation'),
        ),
        migrations.AddField(
            model_name='thana',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district'),
        ),
        migrations.AddField(
            model_name='thana',
            name='upozila',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila'),
        ),
        migrations.AddField(
            model_name='pourosava',
            name='upozila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila'),
        ),
    ]
