# Generated by Django 4.2.4 on 2023-10-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_pourosava_thana_union_delete_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thana',
            name='upozila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila'),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='cityCorporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation'),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='upozila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila'),
        ),
    ]
