# Generated by Django 4.2.4 on 2023-10-09 10:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_thana_upozila_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, verbose_name='Tourist Spot Name in English without Space')),
                ('name', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/TouristSpot/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('cityCorporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila')),
            ],
            options={
                'verbose_name': 'Tourist Spot',
                'verbose_name_plural': 'Tourist Spots',
                'ordering': ['serial'],
            },
        ),
    ]
