# Generated by Django 4.2.4 on 2023-10-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_navigation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navigation',
        ),
    ]
