# Generated by Django 4.2.4 on 2023-10-15 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_rename_image0_post_image_remove_post__image_and_more'),
        ('feature', '0001_initial'),
        ('webInfo', '0007_rename_in_news_navigation_news_and_more'),
        ('categories', '0010_delete_navigation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Continents',
            new_name='Continent',
        ),
    ]
