# Generated by Django 4.2.4 on 2023-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_rename_continents_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citycorporation',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='City Corporation Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Continent Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='country',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Country Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='district',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='District Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='division',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Division Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='newssubcategory',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sub Category Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='poststag',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='turisumspot',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tourist Spot Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='upozila',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Upozila Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='uniqueId',
            field=models.CharField(max_length=50, unique=True, verbose_name='Zip Postal Code + Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='zippostalcode',
            name='zipCode',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
