# Generated by Django 4.2.4 on 2023-10-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_alter_citycorporation_uniqueid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newssubcategory',
            old_name='categoryId',
            new_name='category',
        ),
    ]
