# Generated by Django 4.2.6 on 2023-10-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_rename_categoryid_newssubcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citycorporation',
            options={'ordering': ['name', 'division', 'district'], 'verbose_name': 'City Corporation', 'verbose_name_plural': 'City Corporations'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name', 'division'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['serial', 'title', 'total_view'], 'verbose_name': 'News Category', 'verbose_name_plural': 'News Categories'},
        ),
        migrations.AlterModelOptions(
            name='newssubcategory',
            options={'ordering': ['serial', 'category', 'title', 'total_view'], 'verbose_name': 'News Sub Category', 'verbose_name_plural': 'News Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='poststag',
            options={'ordering': ['title', 'uniqueId', 'total_view'], 'verbose_name': 'Post Tag', 'verbose_name_plural': 'Post Tags'},
        ),
        migrations.AlterModelOptions(
            name='pourosava',
            options={'ordering': ['name', 'upozila', 'district'], 'verbose_name': 'Pourosava', 'verbose_name_plural': 'Pourosavas'},
        ),
        migrations.AlterModelOptions(
            name='thana',
            options={'ordering': ['name', 'district', 'cityCorporation', 'upozila'], 'verbose_name': 'Thana', 'verbose_name_plural': 'Thanas'},
        ),
        migrations.AlterModelOptions(
            name='turisumspot',
            options={'ordering': ['name', 'district', 'cityCorporation', 'upozila', 'zipCode', 'union'], 'verbose_name': 'Turisum Spot', 'verbose_name_plural': 'Turisum Spots'},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ['name', 'upozila'], 'verbose_name': 'Union', 'verbose_name_plural': 'Unions'},
        ),
        migrations.AlterModelOptions(
            name='upozila',
            options={'ordering': ['name', 'district'], 'verbose_name': 'Upozila', 'verbose_name_plural': 'Upozilas'},
        ),
        migrations.AlterModelOptions(
            name='zippostalcode',
            options={'ordering': ['name', 'district', 'cityCorporation', 'upozila'], 'verbose_name': 'Zip Postal Code', 'verbose_name_plural': 'Zip Postal Codes'},
        ),
        migrations.AddField(
            model_name='pourosava',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district'),
        ),
        migrations.AddField(
            model_name='turisumspot',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.union'),
        ),
        migrations.AddField(
            model_name='turisumspot',
            name='zipCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cCode',
            field=models.CharField(max_length=4, unique=True, verbose_name='Country Code'),
        ),
    ]
