# Generated by Django 4.2.4 on 2023-10-09 10:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0002_article'),
        ('reporter', '0001_initial'),
        ('categories', '0008_turisumspot_delete_touristspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, verbose_name='Feature Name in English without Space')),
                ('title', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Feature/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='FeatureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(max_length=50, verbose_name='Category Name in English without Space')),
                ('title', models.CharField(max_length=50)),
                ('sortDetails', models.CharField(blank=True, max_length=200, null=True)),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='News/Categories/Feature/')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('serial', models.PositiveIntegerField(blank=True, default=0)),
                ('total_view', models.PositiveIntegerField(default=0)),
                ('featureId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feature.feature', verbose_name='Feature')),
            ],
            options={
                'verbose_name': 'Feature Category',
                'verbose_name_plural': 'Feature Categories',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='FeaturePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Details')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='Post/images/webp', verbose_name='Image')),
                ('videoLink', models.CharField(blank=True, max_length=200, null=True, verbose_name='Video Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Status')),
                ('editor_reviewed', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Editor Reviewed')),
                ('url', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True, verbose_name='URL(will be auto generated)')),
                ('total_view', models.PositiveIntegerField(default=0, verbose_name='Total View(*Do not edit)')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feature.featurecategory', verbose_name='Feature Category')),
                ('city_corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.citycorporation', verbose_name='City Corporation')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.continents', verbose_name='Continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.country', verbose_name='Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.district', verbose_name='District')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.division', verbose_name='Division')),
                ('featureId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feature.feature', verbose_name='Feature')),
                ('pourosava', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.pourosava', verbose_name='Pourosava')),
                ('related_post', models.ManyToManyField(blank=True, to='feature.featurepost', verbose_name='Related Post Suggation')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporter.reporter', verbose_name='Reporter')),
                ('tag', models.ManyToManyField(blank=True, to='categories.poststag', verbose_name='Tags')),
                ('thana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.thana', verbose_name='Thana')),
                ('turisum_spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.turisumspot', verbose_name='Turisum Spot')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.union', verbose_name='Union')),
                ('upozila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.upozila', verbose_name='Upozila')),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='article.articlewritter', verbose_name='Written By')),
                ('zip_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.zippostalcode', verbose_name='Zip Code')),
            ],
            options={
                'verbose_name': 'Feature Post',
                'verbose_name_plural': 'Feature Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
