# Generated by Django 4.2.6 on 2023-10-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecategory',
            name='details',
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Feature Title'),
        ),
        migrations.AlterField(
            model_name='featurecategory',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Feature Category Title'),
        ),
    ]
