# Generated by Django 4.2.6 on 2023-10-20 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurecategory',
            name='featureId',
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='feature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='feature.feature', to_field='uniqueId', verbose_name='Feature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Feature Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='featurecategory',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Category Name in English without Space'),
        ),
        migrations.AlterField(
            model_name='featurepost',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
