# Generated by Django 4.2.6 on 2023-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_alter_featurepost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='featurecategory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AlterField(
            model_name='feature',
            name='uniqueId',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name in English without Space'),
        ),
    ]
