# Generated by Django 4.2.6 on 2023-10-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0002_alter_feature_uniqueid_alter_featurecategory_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepost',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
