# Generated by Django 4.2.6 on 2023-11-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_feature_status_featurecategory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurepost',
            name='is_highlight_on_section',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Highlight on section'),
        ),
    ]
